global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-informatica-tableau-analytics
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  default:
    parameter_input: taskcat-params.json
    template_file: tableau-awsdata-master.template
